const DECREASE = 'DECREASE';
const INCREASE = 'INCREASE';
const CLEAR_CART = 'CLEAR_CART';
const GET_TOTALS = 'GET_TOTALS';
const TOGGLE_AMOUNT = 'TOGGLE_AMOUNT';
const REMOVE = 'REMOVE';

export { DECREASE, INCREASE, CLEAR_CART, TOGGLE_AMOUNT, GET_TOTALS, REMOVE };
